# English_name, Mainland_name, Taiwan_name, English_title, Mainland_title, Taiwan_title
champions = {'Aatrox': ['Aatrox', '亚托克斯', '厄萨斯', 'the Darkin Blade', '暗裔剑魔', '冥血邪剑'],
             'Ahri': ['Ahri', '阿狸', '阿璃', 'the Nine-Tailed Fox', '九尾妖狐', '九尾妖狐'],
             'Akali': ['Akali', '阿卡丽', '阿卡莉', 'the Fist of Shadow', '暗影之拳', '暗影之拳'],
             'Alistar': ['Alistar', '阿利斯塔', '亚历斯塔', 'the Minotaur', '牛头酋长', '牛头酋长'],
             'Amumu': ['Amumu', '阿木木', '阿姆姆', 'the Sad Mummy', '殇之木乃伊', '殇之木乃伊'],
             'Anivia': ['Anivia', '艾尼维亚', '艾妮维亚', 'the Cryophoenix', '冰晶凤凰', '冰晶凤凰'],
             'Annie': ['Annie', '安妮', '安妮', 'the Dark Child', '黑暗之女', '黑暗之女'],
             'Ashe': ['Ashe', '艾希', '艾希', 'the Frost Archer', '寒冰射手', '冰霜射手'],
             'Aurelion Sol': ['Aurelion Sol', '奥瑞利安·索尔', '翱锐龙兽', 'the Star Forger', '铸星龙王', '星际漫游者'],
             'Azir': ['Azir', '阿兹尔', '阿祁尔', 'the Emperor of the Sands', '沙漠皇帝', '苏瑞玛砂皇'],
             'Bard': ['Bard', '巴德', '巴德', 'theWandering Caretaker', '星界游神', '漂泊守望者'],
             'Blitzcrank': ['Blitzcrank', '布里茨', '布里茨', 'the Great Steam Golem', '蒸汽机器人', '蒸汽巨神兵'],
             'Brand': ['Brand', '布兰德', '布兰德', 'the Burning Vengeance', '复仇焰魂', '复仇业火'],
             'Braum': ['Braum', '布隆', '布朗姆', 'the Heart of the Freljord', '弗雷尔卓德之心', '弗雷尔卓德豪腕'],
             'Caitlyn': ['Caitlyn', '凯特琳', '凯特琳', 'the Sheriff of Piltover', '皮城女警', '执法者'],
             'Camille': ['Camille', '卡蜜尔', '卡蜜儿', 'the Steel Shadow', '青钢影', '钢铁残影'],
             'Cassiopeia': ['Cassiopeia', '卡西奥佩娅', '卡莎碧雅', "the Serpent's Embrace", '魔蛇之拥', '蛇之拥抱'],
             "Cho'Gath": ["Cho'Gath", '科加斯', '科加斯', 'the Terror of the Void', '虚空恐惧', '虚空恐惧'],
             'Corki': ['Corki', '库奇', '库奇', 'the Daring Bombardier', '英勇投弹手', '英勇投弹手'],
             'Darius': ['Darius', '德莱厄斯', '达瑞斯', 'the Hand of Noxus', '诺克萨斯之手', '诺克萨斯之力'],
             'Diana': ['Diana', '戴安娜', '戴安娜', 'Scorn of the Moon', '皎月女神', '轻藐之月'],
             'Dr.Mundo': ['Dr.Mundo', '蒙多医生', '蒙多医生', 'the Madman of Zaun', '祖安狂人', '佐恩狂人'],
             'Draven': ['Draven', '德莱文', '达瑞文', 'the Glorious Executioner', '荣耀行刑官', '处刑娱乐大师'],
             'Ekko': ['Ekko', '艾克', '艾克', 'the Boy Who Shattered Time', '时间刺客', '时空少年'],
             'Elise': ['Elise', '伊莉丝', '伊莉丝', 'the Spider Queen', '蜘蛛女皇', '蜘蛛女王'],
             'Evelynn': ['Evelynn', '伊芙琳', '伊芙琳', 'the Widowmaker', '寡妇制造者', '黑寡妇'],
             'Ezreal': ['Ezreal', '伊泽瑞尔', '伊泽瑞尔', 'the Prodigal Explorer', '探险家', '探险家'],
             'Fiddlesticks': ['Fiddlesticks', '费德提克', '费德提克', 'the Harbinger of Doom', '末日使者', '末日使者'],
             'Fiora': ['Fiora', '菲奥娜', '菲欧拉', 'the Grand Duelist', '无双剑姬', '孤高剑客'],
             'Fizz': ['Fizz', '菲兹', '飞斯', 'the Tidal Trickster', '潮汐海灵', '深海顽童'],
             'Galio': ['Galio', '加里奥', '加里欧', 'the Colossus', '正义巨像', '御国巨像'],
             'Gangplank': ['Gangplank', '普朗克', '刚普朗克', 'the Saltwater Scourge', '海洋之灾', '海洋之灾'],
             'Garen': ['Garen', '盖伦', '盖伦', 'the Might of Demacia', '德玛西亚之力', '蒂玛西亚之力'],
             'Gnar': ['Gnar', '纳尔', '呐儿', 'the Missing Link', '迷失之牙', '失落之子'],
             'Gragas': ['Gragas', '古拉加斯', '古拉格斯', 'the Rabble Rouser', '酒桶', '酒桶之王'],
             'Graves': ['Graves', '格雷福斯', '葛雷夫', 'the Outlaw', '法外狂徒', '亡命之徒'],
             'Hecarim': ['Hecarim', '赫卡里姆', '赫克林', 'the Shadow of War', '战争之影', '战争之影'],
             'Heimerdinger': ['Heimerdinger', '黑默丁格', '汉默丁格', 'the Revered Inventor', '大发明家', '大发明家'],
             'Illaoi': ['Illaoi', '俄洛伊', '伊罗旖', 'the Kraken Priestess','海兽祭司', '海妖祭司'],
             'Irelia': ['Irelia', '艾瑞莉娅', '伊瑞莉雅', 'the Will of the Blades', '刀锋意志', '刀锋意志'],
             'Ivern': ['Ivern', '艾翁', '埃尔文', 'the Green Father', '翠神', '绿林之父'],
             'Janna': ['Janna', '迦娜', '珍娜', "the Storm's Fury", '风暴之怒', '风暴女神'],
             'Jarvan IV': ['Jarvan IV', '嘉文四世', '嘉文四世', 'the Exemplar of Demacia', '德玛西亚皇子', '蒂玛西亚楷模'],
             'Jax': ['Jax', '贾克斯', '贾克斯', 'Grandmaster at Arms', '武器大师', '武器达人'],
             'Jayce': ['Jayce', '杰斯', '杰西', 'the Defender of Tomorrow', '未来守护者', '明日守护者'],
             'Jhin': ['Jhin', '烬', '烬', 'the Virtuoso', '戏命师', '炫技大师'],
             'Jinx': ['Jinx', '金克斯', '吉茵珂丝', 'the Loose Cannon', '暴走萝莉', '暴走重炮'],
             "Kai'sa": ["Kai'sa", '卡莎', '凱莎', 'Daughter of the Void', '虚空之女', '虛空之女'],
             'Kalista': ['Kalista', '卡莉斯塔', '克黎思妲', 'the Spear of Vengeance', '复仇之矛', '复仇之矛'],
             'Karma': ['Karma', '卡尔玛', '卡玛', 'the Enlightened One', '天启者', '魂之启者'],
             'Karthus': ['Karthus', '卡尔萨斯', '卡尔瑟斯', 'the Deathsinger', '死亡颂唱者', '死亡颂唱者'],
             'Kassadin': ['Kassadin', '卡萨丁', '卡萨丁', 'the Void Walker', '虚空行者', '虚空行者'],
             'Katarina': ['Katarina', '卡特琳娜', '卡特莲娜', 'the Sinister Blade', '不祥之刃', '不祥之刃'],
             'Kayle': ['Kayle', '凯尔', '凯尔', 'the Judicator', '审判天使', '审判天使'],
             'Kayn': ['Kayn', '凯隐', '慨影', 'the Shadow Reaper', '影流之镰', '暗魂收割者'],
             'Kennen': ['Kennen', '凯南', '凯能', 'the Heart of the Tempest', '狂暴之心', '狂暴之心'],
             "Kha'Zix": ["Kha'Zix", '卡兹克', '卡力斯', 'the Voidreaver', '虚空掠夺者', '虚空掠食者'],
             'Kindred': ['Kindred', '千珏', '镜爪', 'the Eternal Hunters', '永猎双子', '永恒猎手'],
             'Kled': ['Kled', '克烈', '克雷德', 'the Cantankerous Cavalier', '暴怒骑士', '暴躁骑士'],
             "Kog'Maw": ["Kog'Maw", '克格莫', '寇格魔', 'the Mouth of the Abyss', '深渊巨口', '深渊巨口'],
             'LeBlanc': ['LeBlanc', '乐芙兰', '勒布朗', 'the Deceiver', '诡术妖姬', '欺诈师'],
             'Lee Sin': ['Lee Sin', '李青', '李星', 'the Blind Monk', '盲僧', '盲眼武僧'],
             'Leona': ['Leona', '蕾欧娜', '雷欧娜', 'the Radiant Dawn', '曙光女神', '黎明之光'],
             'Lissandra': ['Lissandra', '丽桑卓', '丽珊卓', 'the Ice Witch', '冰霜女巫', '傲雪巫女'],
             'Lucian': ['Lucian', '卢锡安', '路西恩', 'the Purifier', '圣枪游侠', '驱魔圣枪'],
             'Lulu': ['Lulu', '璐璐', '露璐', 'the Fae Sorceress', '仙灵女巫', '精灵魔法使'],
             'Lux': ['Lux', '拉克丝', '拉克丝', 'the Lady of Luminosity', '光辉女郎', '光之少女'],
             'Malphite': ['Malphite', '墨菲特', '墨菲特', 'Shard of the Monolith', '熔岩巨兽', '幻石碎片'],
             'Malzahar': ['Malzahar', '马尔扎哈', '马尔札哈', 'the Prophet of the Void', '虚空先知', '虚空先知'],
             'Maokai': ['Maokai', '茂凯', '茂凯', 'the Twisted Treant', '扭曲树精', '扭曲树人'],
             'Master Yi': ['Master Yi', '易', '易大师', 'the Wuju Bladesman', '无极剑圣', '无极剑圣'],
             'Miss Fortune': ['Miss Fortune', '厄运小姐', '好运姐', 'the Bounty Hunter', '赏金猎人', '赏金猎人'],
             'Mordekaiser': ['Mordekaiser', '莫德凯撒', '魔斗凯萨', 'the Iron Revenant', '铁铠冥魂', '金属亡灵'],
             'Morgana': ['Morgana', '莫甘娜', '魔甘娜', 'Fallen Angel', '堕落天使', '堕落天使'],
             'Nami': ['Nami', '娜美', '娜米', 'the Tidecaller', '唤潮鲛姬', '海潮之音'],
             'Nasus': ['Nasus', '内瑟斯', '纳瑟斯', 'the Curator of the Sands', '沙漠死神', '沙漠死神'],
             'Nautilus': ['Nautilus', '诺提勒斯', '纳蒂鲁斯', 'the Titan of the Depths', '深海泰坦', '深渊巨人'],
             'Nidalee': ['Nidalee', '奈德丽', '奈德丽', 'the Bestial Huntress', '狂野女猎手', '狂野猎手'],
             'Nocturne': ['Nocturne', '魔腾', '夜曲', 'the Eternal Nightmare', '永恒梦魇', '永恒梦魇'],
             'Nunu': ['Nunu', '努努', '努努', 'the Yeti Rider', '雪人骑士', '雪人骑士'],
             'Olaf': ['Olaf', '奥拉夫', '奥拉夫', 'the Berserker', '狂战士', '狂战士'],
             'Orianna': ['Orianna', '奥莉安娜', '奥莉安娜', 'the Lady of Clockwork', '发条魔灵', '发条少女'],
             'Ornn': ['Ornn', '奥恩', '鄂爾', 'the Fire Below The Mountain', '山隐之焰', '爐心山神'],
             'Pantheon': ['Pantheon', '潘森', '潘森', 'the Artisan of War', '战争之王', '战争之王'],
             'Poppy': ['Poppy', '波比', '波比', 'Keeper of the Hammer', '圣锤之毅', '圣锤守护者'],
             'Pyke': ['Pyke', '派克', '派克', 'the Bloodharbor Ripper', '血港鬼影', '血港開膛手'],
             'Qiyana': ['Qiyana', '奇亚娜', '姬亞娜', 'Empress of the Elements', '元素女皇', '元素女帝'],
             'Quinn': ['Quinn', '奎因', '葵恩', "Demacia's Wings", '德玛西亚之翼', '蒂玛西亚之翼'],
             'Rakan': ['Rakan', '洛', '锐空', 'the Charmer', '幻翎', '惑羽'],
             'Rammus': ['Rammus', '拉莫斯', '拉姆斯', 'the Armordillo', '披甲龙龟', '披甲龙龟'],
             "Rek'Sai": ["Rek'Sai", '雷克塞', '雷珂煞', 'the Void Burrower', '虚空遁地兽', '虚空穿梭者'],
             'Renekton': ['Renekton', '雷克顿', '雷尼克顿', 'the Butcher of the Sands', '荒漠屠夫', '沙漠屠夫'],
             'Rengar': ['Rengar', '雷恩加尔', '雷葛尔', 'the Pridestalker', '傲之追猎者', '傲慢伏击者'],
             'Riven': ['Riven', '锐雯', '雷文', 'the Exile', '放逐之刃', '破刃放逐者'],
             'Rumble': ['Rumble', '兰博', '蓝宝', 'the Mechanized Menace', '机械公敌', '武装机兵'],
             'Ryze': ['Ryze', '瑞兹', '雷兹', 'the Rune Mage', '符文法师', '符文法师'],
             'Sejuani': ['Sejuani', '瑟庄妮', '史瓦妮', "the Winter's Wrath", '北地之怒', '北境之怒'],
             'Shaco': ['Shaco', '萨科', '萨科', 'the Demon Jester', '恶魔小丑', '恶魔小丑'],
             'Shen': ['Shen', '慎', '慎', 'Eye of Twilight', '暮光之眼', '暮光之眼'],
             'Shyvana': ['Shyvana', '希瓦娜', '希瓦娜', 'the Half-Dragon', '龙血武姬', '半龙少女'],
             'Singed': ['Singed', '辛吉德', '辛吉德', 'the Mad Chemist', '炼金术士', '疯狂炼金师'],
             'Sion': ['Sion', '赛恩', '赛恩', 'the Undead Juggernaut', '亡灵战神', '亡灵勇士'],
             'Sivir': ['Sivir', '希维尔', '希维尔', 'the Battle Mistress', '战争女神', '战争女神'],
             'Skarner': ['Skarner', '斯卡纳', '史加纳', 'the Crystal Vanguard', '水晶先锋', '水晶战蝎'],
             'Sona': ['Sona', '娑娜', '索娜', 'Maven of the Strings', '琴瑟仙女', '琴仙'],
             'Soraka': ['Soraka', '索拉卡', '索拉卡', 'the Starchild', '众星之子', '众星之子'],
             'Swain': ['Swain', '斯维因', '斯温', 'the Master Tactician', '策士统领', '谋略家'],
             'Sylas': ['Sylas', '塞拉斯', '賽勒斯', 'the Unshackled', '解脱者', '罪鍊術士'],
             'Syndra': ['Syndra', '辛德拉', '星朵拉', 'the Dark Sovereign', '暗黑元首', '黑暗领主'],
             'Tahm Kench': ['Tahm Kench', '塔姆', '贪啃奇', 'the River King', '河流之王', '河中巨怪'],
             'Taliyah': ['Taliyah', '塔莉垭', '塔莉雅', 'the Stoneweaver', '岩雀', '岩石编织者'],
             'Talon': ['Talon', '泰隆', '塔隆', "the Blade's Shadow", '刀锋之影', '神影刺客'],
             'Taric': ['Taric', '塔里克', '塔里克', 'the Shield of Valoran', '瓦洛兰之盾', '瓦罗然之盾'],
             'Teemo': ['Teemo', '提莫', '提摩', 'the Swift Scout', '迅捷斥候', '迅捷斥候'],
             'Thresh': ['Thresh', '锤石', '瑟雷西', 'the Chain Warden', '魂锁典狱长', '链魂狱长'],
             'Tristana': ['Tristana', '崔丝塔娜', '崔丝塔娜', 'the Yordle Gunner', '班德尔炮手', '约德尔炮手'],
             'Trundle': ['Trundle', '特朗德尔', '特朗德', 'the Troll King', '巨魔之王', '巨魔王'],
             'Tryndamere': ['Tryndamere', '泰达米尔', '泰达米尔', 'the Barbarian King', '蛮族之王', '蛮族之王'],
             'Twisted Fate': ['Twisted Fate', '崔斯特', '逆命', 'the Card Master', '卡牌大师', '卡牌大师'],
             'Twitch': ['Twitch', '图奇', '图奇', 'the Plague Rat', '瘟疫之源', '瘟疫之源'],
             'Udyr': ['Udyr', '乌迪尔', '乌迪尔', 'the Spirit Walker', '兽灵行者', '神灵行者'],
             'Urgot': ['Urgot', '厄加特', '乌尔加特', 'the Dreadnought', '无畏战车', '重装无畏'],
             'Varus': ['Varus', '韦鲁斯', '法洛士', 'the Arrow of Retribution', '惩戒之箭', '惩戒之箭'],
             'Vayne': ['Vayne', '薇恩', '汎', 'the Night Hunter', '暗夜猎手', '暗夜猎人'],
             'Veigar': ['Veigar', '维迦', '维迦', 'the Tiny Master of Evil', '邪恶小法师', '邪恶小法师'],
             "Vel'Koz": ["Vel'Koz", '维克兹', '威寇兹', 'the Eye of the Void', '虚空之眼', '虚空魔眼'],
             'Vi': ['Vi', '蔚', '菲艾', 'the Piltover Enforcer', '皮城执法官', '铁腕特警'],
             'Viktor': ['Viktor', '维克托', '维克特', 'the Machine Herald', '机械先驱', '机械使徒'],
             'Vladimir': ['Vladimir', '弗拉基米尔', '弗拉迪米尔', 'the Crimson Reaper', '猩红收割者', '血色收割者'],
             'Volibear': ['Volibear', '沃利贝尔', '弗利贝尔', "the Thunder's Roar", '雷霆咆哮', '雷霆熊吼'],
             'Warwick': ['Warwick', '沃里克', '沃维克', 'the Uncaged Wrath of Zaun', '祖安之怒', '嗜血狂怒'],
             'Wukong': ['Wukong', '孙悟空', '悟空', 'the Monkey King', '齐天大圣', '齐天大圣'],
             'Xayah': ['Xayah', '霞', '刹雅', 'the Rebel', '逆羽','逆羽'],
             'Xerath': ['Xerath', '泽拉斯', '齐勒斯', 'the Magus Ascendant', '远古巫灵', '远古魔导'],
             'Xin Zhao': ['Xin Zhao', '赵信', '赵信', 'the Seneschal of Demacia', '德邦总管', '蒂玛西亚总管'],
             'Yasuo': ['Yasuo', '亚索', '犽宿', 'the Unforgiven', '疾风剑豪', '放逐浪人'],
             'Yorick': ['Yorick', '约里克', '约瑞科', 'Shepherd of Souls', '牧魂人', '亡魂牧人'],
             'Yuumi': ['Yuumi', '悠米', '悠咪', 'the Magic Cat', '魔法猫咪', '魔法靈貓'],
             'Zac': ['Zac', '扎克', '札克', 'the Secret Weapon', '生化魔人', '魔人'],
             'Zed': ['Zed', '劫', '劫', 'the Master of Shadows', '影流之主', '影忍至尊'],
             'Ziggs': ['Ziggs', '吉格斯', '希格斯', 'the Hexplosives Expert', '爆破鬼才', '魔法爆破专家'],
             'Zilean': ['Zilean', '基兰', '极灵', 'the Chronokeeper', '时光守护者', '时光守护者'],
             'Zoe': ['Zoe', '佐伊', '柔依', 'the Aspect of Twilight', '暮光星灵', '暮光星靈'],
             'Zyra': ['Zyra', '婕拉', '枷萝', 'Rise of the Thorns', '荆棘之兴', '荆棘漫游者']}

# from nga
champions_reverse = {
    
}












