# English_name, Mainland_name, Taiwan_name, English_title, Mainland_title, Taiwan_title
champions = {'Aatrox': ['Aatrox', '亚托克斯', '厄萨斯', 'the Darkin Blade', '暗裔剑魔', '冥血邪剑'],
             'Ahri': ['Ahri', '阿狸', '阿璃', 'the Nine-Tailed Fox', '九尾妖狐', '九尾妖狐'],
             'Akali': ['Akali', '阿卡丽', '阿卡莉', 'the Fist of Shadow', '暗影之拳', '暗影之拳'],
             'Alistar': ['Alistar', '阿利斯塔', '亚历斯塔', 'the Minotaur', '牛头酋长', '牛头酋长'],
             'Amumu': ['Amumu', '阿木木', '阿姆姆', 'the Sad Mummy', '殇之木乃伊', '殇之木乃伊'],
             'Anivia': ['Anivia', '艾尼维亚', '艾妮维亚', 'the Cryophoenix', '冰晶凤凰', '冰晶凤凰'],
             'Annie': ['Annie', '安妮', '安妮', 'the Dark Child', '黑暗之女', '黑暗之女'],
             'Ashe': ['Ashe', '艾希', '艾希', 'the Frost Archer', '寒冰射手', '冰霜射手'],
             'Aurelion Sol': ['Aurelion Sol', '奥瑞利安·索尔', '翱锐龙兽', 'the Star Forger', '铸星龙王', '星际漫游者'],
             'Azir': ['Azir', '阿兹尔', '阿祁尔', 'the Emperor of the Sands', '沙漠皇帝', '苏瑞玛砂皇'],
             'Bard': ['Bard', '巴德', '巴德', 'theWandering Caretaker', '星界游神', '漂泊守望者'],
             'Blitzcrank': ['Blitzcrank', '布里茨', '布里茨', 'the Great Steam Golem', '蒸汽机器人', '蒸汽巨神兵'],
             'Brand': ['Brand', '布兰德', '布兰德', 'the Burning Vengeance', '复仇焰魂', '复仇业火'],
             'Braum': ['Braum', '布隆', '布朗姆', 'the Heart of the Freljord', '弗雷尔卓德之心', '弗雷尔卓德豪腕'],
             'Caitlyn': ['Caitlyn', '凯特琳', '凯特琳', 'the Sheriff of Piltover', '皮城女警', '执法者'],
             'Camille': ['Camille', '卡蜜尔', '卡蜜儿', 'the Steel Shadow', '青钢影', '钢铁残影'],
             'Cassiopeia': ['Cassiopeia', '卡西奥佩娅', '卡莎碧雅', "the Serpent's Embrace", '魔蛇之拥', '蛇之拥抱'],
             "Cho'Gath": ["Cho'Gath", '科加斯', '科加斯', 'the Terror of the Void', '虚空恐惧', '虚空恐惧'],
             'Corki': ['Corki', '库奇', '库奇', 'the Daring Bombardier', '英勇投弹手', '英勇投弹手'],
             'Darius': ['Darius', '德莱厄斯', '达瑞斯', 'the Hand of Noxus', '诺克萨斯之手', '诺克萨斯之力'],
             'Diana': ['Diana', '戴安娜', '戴安娜', 'Scorn of the Moon', '皎月女神', '轻藐之月'],
             'Dr.Mundo': ['Dr.Mundo', '蒙多医生', '蒙多医生', 'the Madman of Zaun', '祖安狂人', '佐恩狂人'],
             'Draven': ['Draven', '德莱文', '达瑞文', 'the Glorious Executioner', '荣耀行刑官', '处刑娱乐大师'],
             'Ekko': ['Ekko', '艾克', '艾克', 'the Boy Who Shattered Time', '时间刺客', '时空少年'],
             'Elise': ['Elise', '伊莉丝', '伊莉丝', 'the Spider Queen', '蜘蛛女皇', '蜘蛛女王'],
             'Evelynn': ['Evelynn', '伊芙琳', '伊芙琳', 'the Widowmaker', '寡妇制造者', '黑寡妇'],
             'Ezreal': ['Ezreal', '伊泽瑞尔', '伊泽瑞尔', 'the Prodigal Explorer', '探险家', '探险家'],
             'Fiddlesticks': ['Fiddlesticks', '费德提克', '费德提克', 'the Harbinger of Doom', '末日使者', '末日使者'],
             'Fiora': ['Fiora', '菲奥娜', '菲欧拉', 'the Grand Duelist', '无双剑姬', '孤高剑客'],
             'Fizz': ['Fizz', '菲兹', '飞斯', 'the Tidal Trickster', '潮汐海灵', '深海顽童'],
             'Galio': ['Galio', '加里奥', '加里欧', 'the Colossus', '正义巨像', '御国巨像'],
             'Gangplank': ['Gangplank', '普朗克', '刚普朗克', 'the Saltwater Scourge', '海洋之灾', '海洋之灾'],
             'Garen': ['Garen', '盖伦', '盖伦', 'the Might of Demacia', '德玛西亚之力', '蒂玛西亚之力'],
             'Gnar': ['Gnar', '纳尔', '呐儿', 'the Missing Link', '迷失之牙', '失落之子'],
             'Gragas': ['Gragas', '古拉加斯', '古拉格斯', 'the Rabble Rouser', '酒桶', '酒桶之王'],
             'Graves': ['Graves', '格雷福斯', '葛雷夫', 'the Outlaw', '法外狂徒', '亡命之徒'],
             'Hecarim': ['Hecarim', '赫卡里姆', '赫克林', 'the Shadow of War', '战争之影', '战争之影'],
             'Heimerdinger': ['Heimerdinger', '黑默丁格', '汉默丁格', 'the Revered Inventor', '大发明家', '大发明家'],
             'Illaoi': ['Illaoi', '俄洛伊', '伊罗旖', 'the Kraken Priestess','海兽祭司', '海妖祭司'],
             'Irelia': ['Irelia', '艾瑞莉娅', '伊瑞莉雅', 'the Will of the Blades', '刀锋意志', '刀锋意志'],
             'Ivern': ['Ivern', '艾翁', '埃尔文', 'the Green Father', '翠神', '绿林之父'],
             'Janna': ['Janna', '迦娜', '珍娜', "the Storm's Fury", '风暴之怒', '风暴女神'],
             'Jarvan IV': ['Jarvan IV', '嘉文四世', '嘉文四世', 'the Exemplar of Demacia', '德玛西亚皇子', '蒂玛西亚楷模'],
             'Jax': ['Jax', '贾克斯', '贾克斯', 'Grandmaster at Arms', '武器大师', '武器达人'],
             'Jayce': ['Jayce', '杰斯', '杰西', 'the Defender of Tomorrow', '未来守护者', '明日守护者'],
             'Jhin': ['Jhin', '烬', '烬', 'the Virtuoso', '戏命师', '炫技大师'],
             'Jinx': ['Jinx', '金克斯', '吉茵珂丝', 'the Loose Cannon', '暴走萝莉', '暴走重炮'],
             "Kai'sa": ["Kai'sa", '卡莎', '凱莎', 'Daughter of the Void', '虚空之女', '虛空之女'],
             'Kalista': ['Kalista', '卡莉斯塔', '克黎思妲', 'the Spear of Vengeance', '复仇之矛', '复仇之矛'],
             'Karma': ['Karma', '卡尔玛', '卡玛', 'the Enlightened One', '天启者', '魂之启者'],
             'Karthus': ['Karthus', '卡尔萨斯', '卡尔瑟斯', 'the Deathsinger', '死亡颂唱者', '死亡颂唱者'],
             'Kassadin': ['Kassadin', '卡萨丁', '卡萨丁', 'the Void Walker', '虚空行者', '虚空行者'],
             'Katarina': ['Katarina', '卡特琳娜', '卡特莲娜', 'the Sinister Blade', '不祥之刃', '不祥之刃'],
             'Kayle': ['Kayle', '凯尔', '凯尔', 'the Judicator', '审判天使', '审判天使'],
             'Kayn': ['Kayn', '凯隐', '慨影', 'the Shadow Reaper', '影流之镰', '暗魂收割者'],
             'Kennen': ['Kennen', '凯南', '凯能', 'the Heart of the Tempest', '狂暴之心', '狂暴之心'],
             "Kha'Zix": ["Kha'Zix", '卡兹克', '卡力斯', 'the Voidreaver', '虚空掠夺者', '虚空掠食者'],
             'Kindred': ['Kindred', '千珏', '镜爪', 'the Eternal Hunters', '永猎双子', '永恒猎手'],
             'Kled': ['Kled', '克烈', '克雷德', 'the Cantankerous Cavalier', '暴怒骑士', '暴躁骑士'],
             "Kog'Maw": ["Kog'Maw", '克格莫', '寇格魔', 'the Mouth of the Abyss', '深渊巨口', '深渊巨口'],
             'LeBlanc': ['LeBlanc', '乐芙兰', '勒布朗', 'the Deceiver', '诡术妖姬', '欺诈师'],
             'Lee Sin': ['Lee Sin', '李青', '李星', 'the Blind Monk', '盲僧', '盲眼武僧'],
             'Leona': ['Leona', '蕾欧娜', '雷欧娜', 'the Radiant Dawn', '曙光女神', '黎明之光'],
             'Lissandra': ['Lissandra', '丽桑卓', '丽珊卓', 'the Ice Witch', '冰霜女巫', '傲雪巫女'],
             'Lucian': ['Lucian', '卢锡安', '路西恩', 'the Purifier', '圣枪游侠', '驱魔圣枪'],
             'Lulu': ['Lulu', '璐璐', '露璐', 'the Fae Sorceress', '仙灵女巫', '精灵魔法使'],
             'Lux': ['Lux', '拉克丝', '拉克丝', 'the Lady of Luminosity', '光辉女郎', '光之少女'],
             'Malphite': ['Malphite', '墨菲特', '墨菲特', 'Shard of the Monolith', '熔岩巨兽', '幻石碎片'],
             'Malzahar': ['Malzahar', '马尔扎哈', '马尔札哈', 'the Prophet of the Void', '虚空先知', '虚空先知'],
             'Maokai': ['Maokai', '茂凯', '茂凯', 'the Twisted Treant', '扭曲树精', '扭曲树人'],
             'Master Yi': ['Master Yi', '易', '易大师', 'the Wuju Bladesman', '无极剑圣', '无极剑圣'],
             'Miss Fortune': ['Miss Fortune', '厄运小姐', '好运姐', 'the Bounty Hunter', '赏金猎人', '赏金猎人'],
             'Mordekaiser': ['Mordekaiser', '莫德凯撒', '魔斗凯萨', 'the Iron Revenant', '铁铠冥魂', '金属亡灵'],
             'Morgana': ['Morgana', '莫甘娜', '魔甘娜', 'Fallen Angel', '堕落天使', '堕落天使'],
             'Nami': ['Nami', '娜美', '娜米', 'the Tidecaller', '唤潮鲛姬', '海潮之音'],
             'Nasus': ['Nasus', '内瑟斯', '纳瑟斯', 'the Curator of the Sands', '沙漠死神', '沙漠死神'],
             'Nautilus': ['Nautilus', '诺提勒斯', '纳蒂鲁斯', 'the Titan of the Depths', '深海泰坦', '深渊巨人'],
             'Nidalee': ['Nidalee', '奈德丽', '奈德丽', 'the Bestial Huntress', '狂野女猎手', '狂野猎手'],
             'Nocturne': ['Nocturne', '魔腾', '夜曲', 'the Eternal Nightmare', '永恒梦魇', '永恒梦魇'],
             'Nunu': ['Nunu', '努努', '努努', 'the Yeti Rider', '雪人骑士', '雪人骑士'],
             'Olaf': ['Olaf', '奥拉夫', '奥拉夫', 'the Berserker', '狂战士', '狂战士'],
             'Orianna': ['Orianna', '奥莉安娜', '奥莉安娜', 'the Lady of Clockwork', '发条魔灵', '发条少女'],
             'Ornn': ['Ornn', '奥恩', '鄂爾', 'the Fire Below The Mountain', '山隐之焰', '爐心山神'],
             'Pantheon': ['Pantheon', '潘森', '潘森', 'the Artisan of War', '战争之王', '战争之王'],
             'Poppy': ['Poppy', '波比', '波比', 'Keeper of the Hammer', '圣锤之毅', '圣锤守护者'],
             'Pyke': ['Pyke', '派克', '派克', 'the Bloodharbor Ripper', '血港鬼影', '血港開膛手'],
             'Qiyana': ['Qiyana', '奇亚娜', '姬亞娜', 'Empress of the Elements', '元素女皇', '元素女帝'],
             'Quinn': ['Quinn', '奎因', '葵恩', "Demacia's Wings", '德玛西亚之翼', '蒂玛西亚之翼'],
             'Rakan': ['Rakan', '洛', '锐空', 'the Charmer', '幻翎', '惑羽'],
             'Rammus': ['Rammus', '拉莫斯', '拉姆斯', 'the Armordillo', '披甲龙龟', '披甲龙龟'],
             "Rek'Sai": ["Rek'Sai", '雷克塞', '雷珂煞', 'the Void Burrower', '虚空遁地兽', '虚空穿梭者'],
             'Renekton': ['Renekton', '雷克顿', '雷尼克顿', 'the Butcher of the Sands', '荒漠屠夫', '沙漠屠夫'],
             'Rengar': ['Rengar', '雷恩加尔', '雷葛尔', 'the Pridestalker', '傲之追猎者', '傲慢伏击者'],
             'Riven': ['Riven', '锐雯', '雷文', 'the Exile', '放逐之刃', '破刃放逐者'],
             'Rumble': ['Rumble', '兰博', '蓝宝', 'the Mechanized Menace', '机械公敌', '武装机兵'],
             'Ryze': ['Ryze', '瑞兹', '雷兹', 'the Rune Mage', '符文法师', '符文法师'],
             'Sejuani': ['Sejuani', '瑟庄妮', '史瓦妮', "the Winter's Wrath", '北地之怒', '北境之怒'],
             'Shaco': ['Shaco', '萨科', '萨科', 'the Demon Jester', '恶魔小丑', '恶魔小丑'],
             'Shen': ['Shen', '慎', '慎', 'Eye of Twilight', '暮光之眼', '暮光之眼'],
             'Shyvana': ['Shyvana', '希瓦娜', '希瓦娜', 'the Half-Dragon', '龙血武姬', '半龙少女'],
             'Singed': ['Singed', '辛吉德', '辛吉德', 'the Mad Chemist', '炼金术士', '疯狂炼金师'],
             'Sion': ['Sion', '赛恩', '赛恩', 'the Undead Juggernaut', '亡灵战神', '亡灵勇士'],
             'Sivir': ['Sivir', '希维尔', '希维尔', 'the Battle Mistress', '战争女神', '战争女神'],
             'Skarner': ['Skarner', '斯卡纳', '史加纳', 'the Crystal Vanguard', '水晶先锋', '水晶战蝎'],
             'Sona': ['Sona', '娑娜', '索娜', 'Maven of the Strings', '琴瑟仙女', '琴仙'],
             'Soraka': ['Soraka', '索拉卡', '索拉卡', 'the Starchild', '众星之子', '众星之子'],
             'Swain': ['Swain', '斯维因', '斯温', 'the Master Tactician', '策士统领', '谋略家'],
             'Sylas': ['Sylas', '塞拉斯', '賽勒斯', 'the Unshackled', '解脱者', '罪鍊術士'],
             'Syndra': ['Syndra', '辛德拉', '星朵拉', 'the Dark Sovereign', '暗黑元首', '黑暗领主'],
             'Tahm Kench': ['Tahm Kench', '塔姆', '贪啃奇', 'the River King', '河流之王', '河中巨怪'],
             'Taliyah': ['Taliyah', '塔莉垭', '塔莉雅', 'the Stoneweaver', '岩雀', '岩石编织者'],
             'Talon': ['Talon', '泰隆', '塔隆', "the Blade's Shadow", '刀锋之影', '神影刺客'],
             'Taric': ['Taric', '塔里克', '塔里克', 'the Shield of Valoran', '瓦洛兰之盾', '瓦罗然之盾'],
             'Teemo': ['Teemo', '提莫', '提摩', 'the Swift Scout', '迅捷斥候', '迅捷斥候'],
             'Thresh': ['Thresh', '锤石', '瑟雷西', 'the Chain Warden', '魂锁典狱长', '链魂狱长'],
             'Tristana': ['Tristana', '崔丝塔娜', '崔丝塔娜', 'the Yordle Gunner', '班德尔炮手', '约德尔炮手'],
             'Trundle': ['Trundle', '特朗德尔', '特朗德', 'the Troll King', '巨魔之王', '巨魔王'],
             'Tryndamere': ['Tryndamere', '泰达米尔', '泰达米尔', 'the Barbarian King', '蛮族之王', '蛮族之王'],
             'Twisted Fate': ['Twisted Fate', '崔斯特', '逆命', 'the Card Master', '卡牌大师', '卡牌大师'],
             'Twitch': ['Twitch', '图奇', '图奇', 'the Plague Rat', '瘟疫之源', '瘟疫之源'],
             'Udyr': ['Udyr', '乌迪尔', '乌迪尔', 'the Spirit Walker', '兽灵行者', '神灵行者'],
             'Urgot': ['Urgot', '厄加特', '乌尔加特', 'the Dreadnought', '无畏战车', '重装无畏'],
             'Varus': ['Varus', '韦鲁斯', '法洛士', 'the Arrow of Retribution', '惩戒之箭', '惩戒之箭'],
             'Vayne': ['Vayne', '薇恩', '汎', 'the Night Hunter', '暗夜猎手', '暗夜猎人'],
             'Veigar': ['Veigar', '维迦', '维迦', 'the Tiny Master of Evil', '邪恶小法师', '邪恶小法师'],
             "Vel'Koz": ["Vel'Koz", '维克兹', '威寇兹', 'the Eye of the Void', '虚空之眼', '虚空魔眼'],
             'Vi': ['Vi', '蔚', '菲艾', 'the Piltover Enforcer', '皮城执法官', '铁腕特警'],
             'Viktor': ['Viktor', '维克托', '维克特', 'the Machine Herald', '机械先驱', '机械使徒'],
             'Vladimir': ['Vladimir', '弗拉基米尔', '弗拉迪米尔', 'the Crimson Reaper', '猩红收割者', '血色收割者'],
             'Volibear': ['Volibear', '沃利贝尔', '弗利贝尔', "the Thunder's Roar", '雷霆咆哮', '雷霆熊吼'],
             'Warwick': ['Warwick', '沃里克', '沃维克', 'the Uncaged Wrath of Zaun', '祖安之怒', '嗜血狂怒'],
             'Wukong': ['Wukong', '孙悟空', '悟空', 'the Monkey King', '齐天大圣', '齐天大圣'],
             'Xayah': ['Xayah', '霞', '刹雅', 'the Rebel', '逆羽','逆羽'],
             'Xerath': ['Xerath', '泽拉斯', '齐勒斯', 'the Magus Ascendant', '远古巫灵', '远古魔导'],
             'Xin Zhao': ['Xin Zhao', '赵信', '赵信', 'the Seneschal of Demacia', '德邦总管', '蒂玛西亚总管'],
             'Yasuo': ['Yasuo', '亚索', '犽宿', 'the Unforgiven', '疾风剑豪', '放逐浪人'],
             'Yorick': ['Yorick', '约里克', '约瑞科', 'Shepherd of Souls', '牧魂人', '亡魂牧人'],
             'Yuumi': ['Yuumi', '悠米', '悠咪', 'the Magic Cat', '魔法猫咪', '魔法靈貓'],
             'Zac': ['Zac', '扎克', '札克', 'the Secret Weapon', '生化魔人', '魔人'],
             'Zed': ['Zed', '劫', '劫', 'the Master of Shadows', '影流之主', '影忍至尊'],
             'Ziggs': ['Ziggs', '吉格斯', '希格斯', 'the Hexplosives Expert', '爆破鬼才', '魔法爆破专家'],
             'Zilean': ['Zilean', '基兰', '极灵', 'the Chronokeeper', '时光守护者', '时光守护者'],
             'Zoe': ['Zoe', '佐伊', '柔依', 'the Aspect of Twilight', '暮光星灵', '暮光星靈'],
             'Zyra': ['Zyra', '婕拉', '枷萝', 'Rise of the Thorns', '荆棘之兴', '荆棘漫游者']}

# from nga
champions_reverse = {'Aatrox': 'Aatrox',
                    '亚托克斯': 'Aatrox',
                    '厄萨斯': 'Aatrox',
                    'the Darkin Blade': 'Aatrox',
                    '暗裔剑魔': 'Aatrox',
                    '冥血邪剑': 'Aatrox',
                    'Ahri': 'Ahri',
                    '阿狸': 'Ahri',
                    '阿璃': 'Ahri',
                    'the Nine-Tailed Fox': 'Ahri',
                    '九尾妖狐': 'Ahri',
                    'Akali': 'Akali',
                    '阿卡丽': 'Akali',
                    '阿卡莉': 'Akali',
                    'the Fist of Shadow': 'Akali',
                    '暗影之拳': 'Akali',
                    'Alistar': 'Alistar',
                    '阿利斯塔': 'Alistar',
                    '亚历斯塔': 'Alistar',
                    'the Minotaur': 'Alistar',
                    '牛头酋长': 'Alistar',
                    'Amumu': 'Amumu',
                    '阿木木': 'Amumu',
                    '阿姆姆': 'Amumu',
                    'the Sad Mummy': 'Amumu',
                    '殇之木乃伊': 'Amumu',
                    'Anivia': 'Anivia',
                    '艾尼维亚': 'Anivia',
                    '艾妮维亚': 'Anivia',
                    'the Cryophoenix': 'Anivia',
                    '冰晶凤凰': 'Anivia',
                    'Annie': 'Annie',
                    '安妮': 'Annie',
                    'the Dark Child': 'Annie',
                    '黑暗之女': 'Annie',
                    'Ashe': 'Ashe',
                    '艾希': 'Ashe',
                    'the Frost Archer': 'Ashe',
                    '寒冰射手': 'Ashe',
                    '冰霜射手': 'Ashe',
                    'Aurelion Sol': 'Aurelion Sol',
                    '奥瑞利安·索尔': 'Aurelion Sol',
                    '翱锐龙兽': 'Aurelion Sol',
                    'the Star Forger': 'Aurelion Sol',
                    '铸星龙王': 'Aurelion Sol',
                    '星际漫游者': 'Aurelion Sol',
                    'Azir': 'Azir',
                    '阿兹尔': 'Azir',
                    '阿祁尔': 'Azir',
                    'the Emperor of the Sands': 'Azir',
                    '沙漠皇帝': 'Azir',
                    '苏瑞玛砂皇': 'Azir',
                    'Bard': 'Bard',
                    '巴德': 'Bard',
                    'theWandering Caretaker': 'Bard',
                    '星界游神': 'Bard',
                    '漂泊守望者': 'Bard',
                    'Blitzcrank': 'Blitzcrank',
                    '布里茨': 'Blitzcrank',
                    'the Great Steam Golem': 'Blitzcrank',
                    '蒸汽机器人': 'Blitzcrank',
                    '蒸汽巨神兵': 'Blitzcrank',
                    'Brand': 'Brand',
                    '布兰德': 'Brand',
                    'the Burning Vengeance': 'Brand',
                    '复仇焰魂': 'Brand',
                    '复仇业火': 'Brand',
                    'Braum':
                    'Braum',
                    '布隆': 'Braum',
                    '布朗姆': 'Braum',
                    'the Heart of the Freljord': 'Braum',
                    '弗雷尔卓德之心': 'Braum',
                    '弗雷尔卓德豪腕': 'Braum',
                    'Caitlyn': 'Caitlyn',
                    '凯特琳': 'Caitlyn',
                    'the Sheriff of Piltover': 'Caitlyn',
                    '皮城女警': 'Caitlyn',
                    '执法者': 'Caitlyn',
                    'Camille': 'Camille',
                    '卡蜜尔': 'Camille',
                    '卡蜜儿': 'Camille',
                    'the Steel Shadow': 'Camille',
                    '青钢影': 'Camille',
                    '钢铁残影': 'Camille',
                    'Cassiopeia': 'Cassiopeia',
                    '卡西奥佩娅': 'Cassiopeia',
                    '卡莎碧雅': 'Cassiopeia',
                    "the Serpent's Embrace": 'Cassiopeia',
                    '魔蛇之拥': 'Cassiopeia',
                    '蛇之拥抱': 'Cassiopeia',
                    "Cho'Gath": "Cho'Gath",
                    '科加斯': "Cho'Gath",
                    'the Terror of the Void': "Cho'Gath",
                    '虚空恐惧': "Cho'Gath",
                    'Corki': 'Corki',
                    '库奇': 'Corki',
                    'the Daring Bombardier': 'Corki',
                    '英勇投弹手': 'Corki',
                    'Darius': 'Darius',
                    '德莱厄斯': 'Darius',
                    '达瑞斯': 'Darius',
                    'the Hand of Noxus': 'Darius',
                    '诺克萨斯之手': 'Darius',
                    '诺克萨斯之力': 'Darius',
                    'Diana': 'Diana',
                    '戴安娜': 'Diana',
                    'Scorn of the Moon': 'Diana',
                    '皎月女神': 'Diana',
                    '轻藐之月': 'Diana',
                    'Dr.Mundo': 'Dr.Mundo',
                    '蒙多医生': 'Dr.Mundo',
                    'the Madman of Zaun': 'Dr.Mundo',
                    '祖安狂人': 'Dr.Mundo',
                    '佐恩狂人': 'Dr.Mundo',
                    'Draven': 'Draven',
                    '德莱文': 'Draven',
                    '达瑞文': 'Draven',
                    'the Glorious Executioner': 'Draven',
                    '荣耀行刑官': 'Draven',
                    '处刑娱乐大师': 'Draven',
                    'Ekko': 'Ekko',
                    '艾克': 'Ekko',
                    'the Boy Who Shattered Time': 'Ekko',
                    '时间刺客': 'Ekko',
                    '时空少年': 'Ekko',
                    'Elise': 'Elise',
                    '伊莉丝': 'Elise',
                    'the Spider Queen': 'Elise',
                    '蜘蛛女皇': 'Elise',
                    '蜘蛛女王': 'Elise',
                    'Evelynn': 'Evelynn',
                    '伊芙琳': 'Evelynn',
                    'the Widowmaker': 'Evelynn',
                    '寡妇制造者': 'Evelynn',
                    '黑寡妇': 'Evelynn',
                    'Ezreal': 'Ezreal',
                    '伊泽瑞尔': 'Ezreal',
                    'the Prodigal Explorer': 'Ezreal',
                    '探险家': 'Ezreal',
                    'Fiddlesticks': 'Fiddlesticks',
                    '费德提克': 'Fiddlesticks',
                    'the Harbinger of Doom': 'Fiddlesticks',
                    '末日使者': 'Fiddlesticks',
                    'Fiora': 'Fiora',
                    '菲奥娜': 'Fiora',
                    '菲欧拉': 'Fiora',
                    'the Grand Duelist': 'Fiora',
                    '无双剑姬': 'Fiora',
                    '孤高剑客': 'Fiora',
                    'Fizz': 'Fizz',
                    '菲兹': 'Fizz',
                    '飞斯': 'Fizz',
                    'the Tidal Trickster': 'Fizz',
                    '潮汐海灵': 'Fizz',
                    '深海顽童': 'Fizz',
                    'Galio': 'Galio',
                    '加里奥': 'Galio',
                    '加里欧': 'Galio',
                    'the Colossus': 'Galio',
                    '正义巨像': 'Galio',
                    '御国巨像': 'Galio',
                    'Gangplank': 'Gangplank',
                    '普朗克': 'Gangplank',
                    '刚普朗克': 'Gangplank',
                    'the Saltwater Scourge': 'Gangplank',
                    '海洋之灾': 'Gangplank',
                    'Garen': 'Garen',
                    '盖伦': 'Garen',
                    'the Might of Demacia': 'Garen',
                    '德玛西亚之力': 'Garen',
                    '蒂玛西亚之力': 'Garen',
                    'Gnar': 'Gnar',
                    '纳尔': 'Gnar',
                    '呐儿': 'Gnar',
                    'the Missing Link': 'Gnar',
                    '迷失之牙': 'Gnar',
                    '失落之子': 'Gnar',
                    'Gragas': 'Gragas',
                    '古拉加斯': 'Gragas',
                    '古拉格斯': 'Gragas',
                    'the Rabble Rouser': 'Gragas',
                    '酒桶': 'Gragas',
                    '酒桶之王': 'Gragas',
                    'Graves': 'Graves',
                    '格雷福斯': 'Graves',
                    '葛雷夫': 'Graves',
                    'the Outlaw': 'Graves',
                    '法外狂徒': 'Graves',
                    '亡命之徒': 'Graves',
                    'Hecarim': 'Hecarim',
                    '赫卡里姆': 'Hecarim',
                    '赫克林': 'Hecarim',
                    'the Shadow of War': 'Hecarim',
                    '战争之影': 'Hecarim',
                    'Heimerdinger': 'Heimerdinger',
                    '黑默丁格': 'Heimerdinger',
                    '汉默丁格': 'Heimerdinger',
                    'the Revered Inventor': 'Heimerdinger',
                    '大发明家': 'Heimerdinger',
                    'Illaoi': 'Illaoi',
                    '俄洛伊': 'Illaoi',
                    '伊罗旖': 'Illaoi',
                    'the Kraken Priestess': 'Illaoi',
                    '海兽祭司': 'Illaoi',
                    '海妖祭司': 'Illaoi',
                    'Irelia': 'Irelia',
                    '艾瑞莉娅': 'Irelia',
                    '伊瑞莉雅': 'Irelia',
                    'the Will of the Blades': 'Irelia',
                    '刀锋意志': 'Irelia',
                    'Ivern': 'Ivern',
                    '艾翁': 'Ivern',
                    '埃尔文': 'Ivern',
                    'the Green Father': 'Ivern',
                    '翠神': 'Ivern',
                    '绿林之父': 'Ivern',
                    'Janna': 'Janna',
                    '迦娜': 'Janna',
                    '珍娜': 'Janna',
                    "the Storm's Fury": 'Janna',
                    '风暴之怒': 'Janna',
                    '风暴女神': 'Janna',
                    'Jarvan IV': 'Jarvan IV',
                    '嘉文四世': 'Jarvan IV',
                    'the Exemplar of Demacia': 'Jarvan IV',
                    '德玛西亚皇子': 'Jarvan IV',
                    '蒂玛西亚楷模': 'Jarvan IV',
                    'Jax': 'Jax',
                    '贾克斯': 'Jax',
                    'Grandmaster at Arms': 'Jax',
                    '武器大师': 'Jax',
                    '武器达人': 'Jax',
                    'Jayce': 'Jayce',
                    '杰斯': 'Jayce',
                    '杰西': 'Jayce',
                    'the Defender of Tomorrow': 'Jayce',
                    '未来守护者': 'Jayce',
                    '明日守护者': 'Jayce',
                    'Jhin': 'Jhin',
                    '烬': 'Jhin',
                    'the Virtuoso': 'Jhin',
                    '戏命师': 'Jhin',
                    '炫技大师': 'Jhin',
                    'Jinx': 'Jinx',
                    '金克斯': 'Jinx',
                    '吉茵珂丝': 'Jinx',
                    'the Loose Cannon': 'Jinx',
                    '暴走萝莉': 'Jinx',
                    '暴走重炮': 'Jinx',
                    "Kai'sa": "Kai'sa",
                    '卡莎': "Kai'sa",
                    '凱莎': "Kai'sa",
                    'Daughter of the Void': "Kai'sa",
                    '虚空之女': "Kai'sa",
                    '虛空之女': "Kai'sa",
                    'Kalista': 'Kalista',
                    '卡莉斯塔': 'Kalista',
                    '克黎思妲': 'Kalista',
                    'the Spear of Vengeance': 'Kalista',
                    '复仇之矛': 'Kalista',
                    'Karma': 'Karma',
                    '卡尔玛': 'Karma',
                    '卡玛': 'Karma',
                    'the Enlightened One': 'Karma',
                    '天启者': 'Karma',
                    '魂之启者': 'Karma',
                    'Karthus': 'Karthus',
                    '卡尔萨斯': 'Karthus',
                    '卡尔瑟斯': 'Karthus',
                    'the Deathsinger': 'Karthus',
                    '死亡颂唱者': 'Karthus',
                    'Kassadin': 'Kassadin',
                    '卡萨丁': 'Kassadin',
                    'the Void Walker': 'Kassadin',
                    '虚空行者': 'Kassadin',
                    'Katarina': 'Katarina',
                    '卡特琳娜': 'Katarina',
                    '卡特莲娜': 'Katarina',
                    'the Sinister Blade': 'Katarina',
                    '不祥之刃': 'Katarina',
                    'Kayle': 'Kayle',
                    '凯尔': 'Kayle',
                    'the Judicator': 'Kayle',
                    '审判天使': 'Kayle',
                    'Kayn': 'Kayn',
                    '凯隐': 'Kayn',
                    '慨影': 'Kayn',
                    'the Shadow Reaper':
                    'Kayn',
                    '影流之镰': 'Kayn',
                    '暗魂收割者': 'Kayn',
                    'Kennen': 'Kennen',
                    '凯南': 'Kennen',
                    '凯能': 'Kennen',
                    'the Heart of the Tempest': 'Kennen',
                    '狂暴之心':
                    'Kennen',
                    "Kha'Zix": "Kha'Zix",
                    '卡兹克': "Kha'Zix",
                    '卡力斯': "Kha'Zix",
                    'the Voidreaver': "Kha'Zix",
                    '虚空掠夺者': "Kha'Zix",
                    '虚空掠食者': "Kha'Zix",
                    'Kindred': 'Kindred',
                    '千珏': 'Kindred',
                    '镜爪': 'Kindred',
                    'the Eternal Hunters': 'Kindred',
                    '永猎双子': 'Kindred',
                    '永恒猎手': 'Kindred',
                    'Kled': 'Kled',
                    '克烈': 'Kled',
                    '克雷德': 'Kled',
                    'the Cantankerous Cavalier': 'Kled',
                    '暴怒骑士': 'Kled',
                    '暴躁骑士': 'Kled',
                    "Kog'Maw": "Kog'Maw",
                    '克格莫': "Kog'Maw",
                    '寇格魔': "Kog'Maw",
                    'the Mouth of the Abyss': "Kog'Maw",
                    '深渊巨口': "Kog'Maw",
                    'LeBlanc': 'LeBlanc',
                    '乐芙兰': 'LeBlanc',
                    '勒布朗': 'LeBlanc',
                    'the Deceiver':
                    'LeBlanc',
                    '诡术妖姬': 'LeBlanc',
                    '欺诈师': 'LeBlanc',
                    'Lee Sin': 'Lee Sin',
                    '李青': 'Lee Sin',
                    '李星': 'Lee Sin',
                    'the Blind Monk': 'Lee Sin',
                    '盲僧': 'Lee Sin',
                    '盲眼武僧': 'Lee Sin',
                    'Leona': 'Leona',
                    '蕾欧娜': 'Leona',
                    '雷欧娜': 'Leona',
                    'the Radiant Dawn': 'Leona',
                    '曙光女神': 'Leona',
                    '黎明之光': 'Leona',
                    'Lissandra': 'Lissandra',
                    '丽桑卓': 'Lissandra',
                    '丽珊卓': 'Lissandra',
                    'the Ice Witch': 'Lissandra',
                    '冰霜女巫': 'Lissandra',
                    '傲雪巫女': 'Lissandra',
                    'Lucian': 'Lucian',
                    '卢锡安': 'Lucian',
                    '路西恩': 'Lucian',
                    'the Purifier': 'Lucian',
                    '圣枪游侠': 'Lucian',
                    '驱魔圣枪': 'Lucian',
                    'Lulu': 'Lulu',
                    '璐璐': 'Lulu',
                    '露璐': 'Lulu',
                    'the Fae Sorceress': 'Lulu',
                    '仙灵女巫': 'Lulu',
                    '精灵魔法使': 'Lulu',
                    'Lux': 'Lux',
                    '拉克丝': 'Lux',
                    'the Lady of Luminosity': 'Lux',
                    '光辉女郎': 'Lux',
                    '光之少女': 'Lux',
                    'Malphite': 'Malphite',
                    '墨菲特': 'Malphite',
                    'Shard of the Monolith': 'Malphite',
                    '熔岩巨兽': 'Malphite',
                    '幻石碎片':
                    'Malphite',
                    'Malzahar': 'Malzahar',
                    '马尔扎哈': 'Malzahar',
                    '马尔札哈': 'Malzahar',
                    'the Prophet of the Void': 'Malzahar',
                    '虚空先知': 'Malzahar',
                    'Maokai': 'Maokai',
                    '茂凯': 'Maokai',
                    'the Twisted Treant': 'Maokai',
                    '扭曲树精': 'Maokai',
                    '扭曲树人': 'Maokai',
                    'Master Yi': 'Master Yi',
                    '易': 'Master Yi',
                    '易大师': 'Master Yi',
                    'the Wuju Bladesman': 'Master Yi',
                    '无极剑圣': 'Master Yi',
                    'Miss Fortune': 'Miss Fortune',
                    '厄运小姐': 'Miss Fortune',
                    '好运姐': 'Miss Fortune',
                    'the Bounty Hunter': 'Miss Fortune',
                    '赏金猎人': 'Miss Fortune',
                    'Mordekaiser': 'Mordekaiser',
                    '莫德凯撒': 'Mordekaiser',
                    '魔斗凯萨': 'Mordekaiser',
                    'the Iron Revenant': 'Mordekaiser',
                    '铁铠冥魂': 'Mordekaiser',
                    '金属亡灵': 'Mordekaiser',
                    'Morgana': 'Morgana',
                    '莫甘娜': 'Morgana',
                    '魔甘娜': 'Morgana',
                    'Fallen Angel': 'Morgana',
                    '堕落天使': 'Morgana',
                    'Nami': 'Nami',
                    '娜美': 'Nami',
                    '娜米': 'Nami',
                    'the Tidecaller': 'Nami',
                    '唤潮鲛姬': 'Nami',
                    '海潮之音': 'Nami',
                    'Nasus': 'Nasus',
                    '内瑟斯': 'Nasus',
                    '纳瑟斯': 'Nasus',
                    'the Curator of the Sands': 'Nasus',
                    '沙漠死神': 'Nasus',
                    'Nautilus': 'Nautilus',
                    '诺提勒斯': 'Nautilus',
                    '纳蒂鲁斯': 'Nautilus',
                    'the Titan of the Depths': 'Nautilus',
                    '深海泰坦': 'Nautilus',
                    '深渊巨人': 'Nautilus',
                    'Nidalee': 'Nidalee',
                    '奈德丽':
                    'Nidalee',
                    'the Bestial Huntress': 'Nidalee',
                    '狂野女猎手': 'Nidalee',
                    '狂野猎手': 'Nidalee',
                    'Nocturne': 'Nocturne',
                    '魔腾': 'Nocturne',
                    '夜曲': 'Nocturne',
                    'the Eternal Nightmare': 'Nocturne',
                    '永恒梦魇': 'Nocturne',
                    'Nunu': 'Nunu',
                    '努努': 'Nunu',
                    'the Yeti Rider': 'Nunu',
                    '雪人骑士': 'Nunu',
                    'Olaf': 'Olaf',
                    '奥拉夫': 'Olaf',
                    'the Berserker': 'Olaf',
                    '狂战士': 'Olaf',
                    'Orianna': 'Orianna',
                    '奥莉安娜': 'Orianna',
                    'the Lady of Clockwork': 'Orianna',
                    '发条魔灵': 'Orianna',
                    '发条少女': 'Orianna',
                    'Ornn': 'Ornn',
                    '奥恩': 'Ornn',
                    '鄂爾': 'Ornn',
                    'the Fire Below The Mountain': 'Ornn',
                    '山隐之焰': 'Ornn',
                    '爐心山神': 'Ornn',
                    'Pantheon': 'Pantheon',
                    '潘森': 'Pantheon',
                    'the Artisan of War': 'Pantheon',
                    '战争之王': 'Pantheon',
                    'Poppy': 'Poppy',
                    '波比': 'Poppy',
                    'Keeper of the Hammer': 'Poppy',
                    '圣锤之毅': 'Poppy',
                    '圣锤守护者': 'Poppy',
                    'Pyke': 'Pyke',
                    '派克': 'Pyke',
                    'the Bloodharbor Ripper': 'Pyke',
                    '血港鬼影': 'Pyke',
                    '血港開膛手': 'Pyke',
                    'Qiyana': 'Qiyana',
                    '奇亚娜': 'Qiyana',
                    '姬亞娜': 'Qiyana',
                    'Empress of the Elements': 'Qiyana',
                    '元素女皇': 'Qiyana',
                    '元素女帝': 'Qiyana',
                    'Quinn': 'Quinn',
                    '奎因': 'Quinn',
                    '葵恩': 'Quinn',
                    "Demacia's Wings": 'Quinn',
                    '德玛西亚之翼': 'Quinn',
                    '蒂玛西亚之翼': 'Quinn',
                    'Rakan': 'Rakan',
                    '洛': 'Rakan',
                    '锐空': 'Rakan',
                    'the Charmer': 'Rakan',
                    '幻翎': 'Rakan',
                    '惑羽': 'Rakan',
                    'Rammus': 'Rammus',
                    '拉莫斯': 'Rammus',
                    '拉姆斯': 'Rammus',
                    'the Armordillo': 'Rammus',
                    '披甲龙龟': 'Rammus',
                    "Rek'Sai": "Rek'Sai",
                    '雷克塞': "Rek'Sai",
                    '雷珂煞': "Rek'Sai",
                    'the Void Burrower': "Rek'Sai",
                    '虚空遁地兽': "Rek'Sai",
                    '虚空穿梭者': "Rek'Sai",
                    'Renekton': 'Renekton',
                    '雷克顿': 'Renekton',
                    '雷尼克顿': 'Renekton',
                    'the Butcher of the Sands': 'Renekton',
                    '荒漠屠夫': 'Renekton',
                    '沙漠屠夫': 'Renekton',
                    'Rengar': 'Rengar',
                    '雷恩加尔': 'Rengar',
                    '雷葛尔': 'Rengar',
                    'the Pridestalker': 'Rengar',
                    '傲之追猎者': 'Rengar',
                    '傲慢伏击者': 'Rengar',
                    'Riven': 'Riven',
                    '锐雯': 'Riven',
                    '雷文': 'Riven',
                    'the Exile': 'Riven',
                    '放逐之刃': 'Riven',
                    '破刃放逐者': 'Riven',
                    'Rumble': 'Rumble',
                    '兰博': 'Rumble',
                    '蓝宝': 'Rumble',
                    'the Mechanized Menace': 'Rumble',
                    '机械公敌': 'Rumble',
                    '武装机兵': 'Rumble',
                    'Ryze': 'Ryze',
                    '瑞兹': 'Ryze',
                    '雷兹': 'Ryze',
                    'the Rune Mage': 'Ryze',
                    '符文法师': 'Ryze',
                    'Sejuani': 'Sejuani',
                    '瑟庄妮': 'Sejuani',
                    '史瓦妮': 'Sejuani',
                    "the Winter's Wrath": 'Sejuani',
                    '北地之怒': 'Sejuani',
                    '北境之怒': 'Sejuani',
                    'Shaco': 'Shaco',
                    '萨科': 'Shaco',
                    'the Demon Jester': 'Shaco',
                    '恶魔小丑': 'Shaco',
                    'Shen': 'Shen',
                    '慎': 'Shen',
                    'Eye of Twilight': 'Shen',
                    '暮光之眼': 'Shen',
                    'Shyvana': 'Shyvana',
                    '希瓦娜': 'Shyvana',
                    'the Half-Dragon': 'Shyvana',
                    '龙血武姬': 'Shyvana',
                    '半龙少女': 'Shyvana',
                    'Singed': 'Singed',
                    '辛吉德': 'Singed',
                    'the Mad Chemist': 'Singed',
                    '炼金术士': 'Singed',
                    '疯狂炼金师': 'Singed',
                    'Sion': 'Sion',
                    '赛恩': 'Sion',
                    'the Undead Juggernaut': 'Sion',
                    '亡灵战神': 'Sion',
                    '亡灵勇士': 'Sion',
                    'Sivir': 'Sivir',
                    '希维尔': 'Sivir',
                    'the Battle Mistress': 'Sivir',
                    '战争女神': 'Sivir',
                    'Skarner': 'Skarner',
                    '斯卡纳': 'Skarner',
                    '史加纳': 'Skarner',
                    'the Crystal Vanguard': 'Skarner',
                    '水晶先锋': 'Skarner',
                    '水晶战蝎': 'Skarner',
                    'Sona': 'Sona',
                    '娑娜': 'Sona',
                    '索娜': 'Sona',
                    'Maven of the Strings': 'Sona',
                    '琴瑟仙女': 'Sona',
                    '琴仙': 'Sona',
                    'Soraka': 'Soraka',
                    '索拉卡': 'Soraka',
                    'the Starchild': 'Soraka',
                    '众星之子': 'Soraka',
                    'Swain': 'Swain',
                    '斯维因': 'Swain',
                    '斯温': 'Swain',
                    'the Master Tactician': 'Swain',
                    '策士统领': 'Swain',
                    '谋略家':
                    'Swain',
                    'Sylas': 'Sylas',
                    '塞拉斯': 'Sylas',
                    '賽勒斯': 'Sylas',
                    'the Unshackled': 'Sylas',
                    '解脱者': 'Sylas',
                    '罪鍊術士': 'Sylas',
                    'Syndra': 'Syndra',
                    '辛德拉': 'Syndra',
                    '星朵拉': 'Syndra',
                    'the Dark Sovereign': 'Syndra',
                    '暗黑元首': 'Syndra',
                    '黑暗领主': 'Syndra',
                    'Tahm Kench': 'Tahm Kench',
                    '塔姆': 'Tahm Kench',
                    '贪啃奇': 'Tahm Kench',
                    'the River King': 'Tahm Kench',
                    '河流之王': 'Tahm Kench',
                    '河中巨怪': 'Tahm Kench',
                    'Taliyah': 'Taliyah',
                    '塔莉垭': 'Taliyah',
                    '塔莉雅': 'Taliyah',
                    'the Stoneweaver': 'Taliyah',
                    '岩雀': 'Taliyah',
                    '岩石编织者': 'Taliyah',
                    'Talon': 'Talon',
                    '泰隆': 'Talon',
                    '塔隆': 'Talon',
                    "the Blade's Shadow": 'Talon',
                    '刀锋之影': 'Talon',
                    '神影刺客': 'Talon',
                    'Taric': 'Taric',
                    '塔里克': 'Taric',
                    'the Shield of Valoran': 'Taric',
                    '瓦洛兰之盾': 'Taric',
                    '瓦罗然之盾': 'Taric',
                    'Teemo': 'Teemo',
                    '提莫': 'Teemo',
                    '提摩': 'Teemo',
                    'the Swift Scout': 'Teemo',
                    '迅捷斥候': 'Teemo',
                    'Thresh': 'Thresh',
                    '锤石':
                    'Thresh',
                    '瑟雷西': 'Thresh',
                    'the Chain Warden': 'Thresh',
                    '魂锁典狱长': 'Thresh',
                    '链魂狱长': 'Thresh',
                    'Tristana': 'Tristana',
                    '崔丝塔娜': 'Tristana',
                    'the Yordle Gunner': 'Tristana',
                    '班德尔炮手': 'Tristana',
                    '约德尔炮手': 'Tristana',
                    'Trundle': 'Trundle',
                    '特朗德尔': 'Trundle',
                    '特朗德': 'Trundle',
                    'the Troll King': 'Trundle',
                    '巨魔之王': 'Trundle',
                    '巨魔王': 'Trundle',
                    'Tryndamere': 'Tryndamere',
                    '泰达米尔': 'Tryndamere',
                    'the Barbarian King': 'Tryndamere',
                    '蛮族之王': 'Tryndamere',
                    'Twisted Fate': 'Twisted Fate',
                    '崔斯特': 'Twisted Fate',
                    '逆命': 'Twisted Fate',
                    'the Card Master': 'Twisted Fate',
                    '卡牌大师': 'Twisted Fate',
                    'Twitch': 'Twitch',
                    '图奇': 'Twitch',
                    'the Plague Rat': 'Twitch',
                    '瘟疫之源': 'Twitch',
                    'Udyr': 'Udyr',
                    '乌迪尔': 'Udyr',
                    'the Spirit Walker': 'Udyr',
                    '兽灵行者': 'Udyr',
                    '神灵行者': 'Udyr',
                    'Urgot': 'Urgot',
                    '厄加特': 'Urgot',
                    '乌尔加特': 'Urgot',
                    'the Dreadnought': 'Urgot',
                    '无畏战车': 'Urgot',
                    '重装无畏': 'Urgot',
                    'Varus': 'Varus',
                    '韦鲁斯': 'Varus',
                    '法洛士': 'Varus',
                    'the Arrow of Retribution': 'Varus',
                    '惩戒之箭': 'Varus',
                    'Vayne': 'Vayne',
                    '薇恩': 'Vayne',
                    '汎': 'Vayne',
                    'the Night Hunter': 'Vayne',
                    '暗夜猎手': 'Vayne',
                    '暗夜猎人': 'Vayne',
                    'Veigar': 'Veigar',
                    '维迦': 'Veigar',
                    'the Tiny Master of Evil': 'Veigar',
                    '邪恶小法师': 'Veigar',
                    "Vel'Koz": "Vel'Koz",
                    '维克兹': "Vel'Koz",
                    '威寇兹': "Vel'Koz",
                    'the Eye of the Void': "Vel'Koz",
                    '虚空之眼': "Vel'Koz",
                    '虚空魔眼': "Vel'Koz",
                    'Vi': 'Vi',
                    '蔚': 'Vi',
                    '菲艾': 'Vi',
                    'the Piltover Enforcer': 'Vi',
                    '皮城执法官': 'Vi',
                    '铁腕特警': 'Vi',
                    'Viktor': 'Viktor',
                    '维克托': 'Viktor',
                    '维克特': 'Viktor',
                    'the Machine Herald': 'Viktor',
                    '机械先驱': 'Viktor',
                    '机械使徒': 'Viktor',
                    'Vladimir': 'Vladimir',
                    '弗拉基米尔': 'Vladimir',
                    '弗拉迪米尔': 'Vladimir',
                    'the Crimson Reaper': 'Vladimir',
                    '猩红收割者': 'Vladimir',
                    '血色收割者': 'Vladimir',
                    'Volibear': 'Volibear',
                    '沃利贝尔': 'Volibear',
                    '弗利贝尔': 'Volibear',
                    "the Thunder's Roar": 'Volibear',
                    '雷霆咆哮': 'Volibear',
                    '雷霆熊吼': 'Volibear',
                    'Warwick': 'Warwick',
                    '沃里克': 'Warwick',
                    '沃维克': 'Warwick',
                    'the Uncaged Wrath of Zaun': 'Warwick',
                    '祖安之怒': 'Warwick',
                    '嗜血狂怒': 'Warwick',
                    'Wukong': 'Wukong',
                    '孙悟空': 'Wukong',
                    '悟空': 'Wukong',
                    'the Monkey King': 'Wukong',
                    '齐天大圣': 'Wukong',
                    'Xayah': 'Xayah',
                    '霞': 'Xayah',
                    '刹雅': 'Xayah',
                    'the Rebel': 'Xayah',
                    '逆羽': 'Xayah',
                    'Xerath': 'Xerath',
                    '泽拉斯': 'Xerath',
                    '齐勒斯': 'Xerath',
                    'the Magus Ascendant': 'Xerath',
                    '远古巫灵': 'Xerath',
                    '远古魔导': 'Xerath',
                    'Xin Zhao': 'Xin Zhao',
                    '赵信': 'Xin Zhao',
                    'the Seneschal of Demacia': 'Xin Zhao',
                    '德邦总管': 'Xin Zhao',
                    '蒂玛西亚总管': 'Xin Zhao',
                    'Yasuo': 'Yasuo',
                    '亚索': 'Yasuo',
                    '犽宿': 'Yasuo',
                    'the Unforgiven': 'Yasuo',
                    '疾风剑豪': 'Yasuo',
                    '放逐浪人': 'Yasuo',
                    'Yorick': 'Yorick',
                    '约里克': 'Yorick',
                    '约瑞科': 'Yorick',
                    'Shepherd of Souls': 'Yorick',
                    '牧魂人': 'Yorick',
                    '亡魂牧人': 'Yorick',
                    'Yuumi': 'Yuumi',
                    '悠米': 'Yuumi',
                    '悠咪': 'Yuumi',
                    'the Magic Cat': 'Yuumi',
                    '魔法猫咪': 'Yuumi',
                    '魔法靈貓': 'Yuumi',
                    'Zac': 'Zac',
                    '扎克': 'Zac',
                    '札克': 'Zac',
                    'the Secret Weapon': 'Zac',
                    '生化魔人': 'Zac',
                    '魔人': 'Zac',
                    'Zed': 'Zed',
                    '劫': 'Zed',
                    'the Master of Shadows': 'Zed',
                    '影流之主': 'Zed',
                    '影忍至尊': 'Zed',
                    'Ziggs': 'Ziggs',
                    '吉格斯': 'Ziggs',
                    '希格斯': 'Ziggs',
                    'the Hexplosives Expert': 'Ziggs',
                    '爆破鬼才': 'Ziggs',
                    '魔法爆破专家': 'Ziggs',
                    'Zilean': 'Zilean',
                    '基兰': 'Zilean',
                    '极灵': 'Zilean',
                    'the Chronokeeper': 'Zilean',
                    '时光守护者':
                    'Zilean',
                    'Zoe': 'Zoe',
                    '佐伊': 'Zoe',
                    '柔依': 'Zoe',
                    'the Aspect of Twilight': 'Zoe',
                    '暮光星灵': 'Zoe',
                    '暮光星靈': 'Zoe',
                    'Zyra': 'Zyra',
                    '婕拉': 'Zyra',
                    '枷萝': 'Zyra',
                    'Rise of the Thorns': 'Zyra',
                    '荆棘之兴': 'Zyra',
                    '荆棘漫游者': 'Zyra',
                    '沙皇': 'Azir',
                    'NOC': 'Nocturne',
                    'noc': 'Nocturne',
                    '流浪': 'Ryze',
                    '光头': 'Ryze',
                    '瑞文': 'Riven',
                    '狮子狗': 'Rengar',
                    '卡牌': 'Twisted Fate',
                    'TF': 'Twisted Fate',
                    '大流士': 'Darius',
                    '诺手': 'Darius',
                    '女枪': 'Miss Fortune',
                    '病娇': 'Jinx',
                    '吸血鬼': 'Vladimir',
                    'Vlad': 'Vladimir',
                    '火女': 'Annie',
                    '露露': 'Lulu'}